### ISSUE TITLE
Linking from libhebic++.so.3.10.0 to libhebic++.so

### ISSUE THREAD

**Issue by raphael-jms** [HebiRobotics/hebi_cpp_api_ros#16]
Hello, I experienced an issue during the install of the hebi_ros2_example package: Install via
`source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build --symlink-install`
resulted in 
`Package 'hebi_cpp_api' exports the library 'hebic++' which couldn't be found`.

Further investigation showed that the file `libhebic++.so.3.10.0` was correctly built, but not linked to `libhebic++.so` which caused the 'not found'-error. Manually linking and installing with
```
source /opt/ros/${ROS_DISTRO}/setup.bash \
    && colcon build --symlink-install --packages-select hebi_cpp_api hebi_msgs \
    && cd install/hebi_cpp_api/lib \
    && ln -s libhebic++.so.3.10.0 libhebic++.so \
    && cd /ros2_ws \
    && source install/setup.bash \
    && colcon build --symlink-install
```
resulted in a successful build.

Platform: Ubuntu 22.04
ROS version: Humble

I think the proper way to deal with this would be to use the SOVERSION property of `set_target_properties` in CMakeLists.txt

**Comment by hr1799** [comment]
This should be fixed with the new merge; please confirm. Can close the issue after confirmation.

**Comment by raphael-jms** [comment]
It is, thank you!
